services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - type: bind
        source: /data/ditteograsmus
        target: /app/ditteograsmus
        is_directory: true
