version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - /tmp/ditteograsmus:/app/uploads  # Bind mount to host directory
    restart: always

volumes:
  uploads:
